In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np

In [3]:
from handmadeML.optimizers.adam import AdamOptimizer

In [4]:
weights=[np.ones((5,4)), np.zeros((4,1))]
bias=[np.ones(4),np.ones(1)]
ad=AdamOptimizer((weights, bias))

In [5]:
a, b = ad.get_update((np.ones((5,4)), np.zeros((4,1))))

[[0.001 0.001 0.001 0.001]
 [0.001 0.001 0.001 0.001]
 [0.001 0.001 0.001 0.001]
 [0.001 0.001 0.001 0.001]
 [0.001 0.001 0.001 0.001]]


In [6]:
a

[array([[-0.001, -0.001, -0.001, -0.001],
        [-0.001, -0.001, -0.001, -0.001],
        [-0.001, -0.001, -0.001, -0.001],
        [-0.001, -0.001, -0.001, -0.001],
        [-0.001, -0.001, -0.001, -0.001]]),
 array([[-0.001, -0.001, -0.001, -0.001],
        [-0.001, -0.001, -0.001, -0.001],
        [-0.001, -0.001, -0.001, -0.001],
        [-0.001, -0.001, -0.001, -0.001]])]

In [7]:
b

[array([-0., -0., -0., -0.]), array([-0.])]

In [8]:
from handmadeML.neuralnets.models import HandmadeNN

In [9]:
my_nn=HandmadeNN(input_dim = 2)
my_nn.set_loss('mse')

In [10]:
my_nn.add_dense_layer(1, 'linear',)
X= np.ones((10_000, 2))
y= np.zeros((10_000,1))

In [11]:
optimizer = AdamOptimizer ((my_nn.weights, my_nn.bias))

In [12]:
optimizer.v

[[array([[0., 0.]])], [array([0.])]]

In [13]:
gradient_weights, gradient_bias\
                    = my_nn.compute_backpropagation(X[0:10],y[0:10])

In [14]:
gradient_weights

[array([[-1.46597145, -1.46597145]])]

In [43]:
weights_update, bias_update = optimizer.get_update((gradient_weights,gradient_bias))

[[0.13192951 0.13192951]]


In [45]:
bias_update

[array([0.001])]

In [28]:
[[np.zeros_like(w) for w in l] for l in params]

NameError: name 'params' is not defined

In [46]:
my_nn.fit(X,y, loss='mse',optimizer_type='adam', batch_size=7, n_epochs=2)

initial loss: 6.609681438799843
[[0.02643873 0.02643873]]
[[0.05278935 0.05278935]]
[[0.07905202 0.07905202]]
[[0.10522692 0.10522692]]
[[0.1313142 0.1313142]]
[[0.15731403 0.15731403]]
[[0.18322658 0.18322658]]
[[0.20905201 0.20905201]]
[[0.23479049 0.23479049]]
[[0.26044219 0.26044219]]
[[0.28600729 0.28600729]]
[[0.31148594 0.31148594]]
[[0.33687833 0.33687833]]
[[0.36218462 0.36218462]]
[[0.38740499 0.38740499]]
[[0.41253962 0.41253962]]
[[0.43758868 0.43758868]]
[[0.46255234 0.46255234]]
[[0.48743079 0.48743079]]
[[0.5122242 0.5122242]]
[[0.53693274 0.53693274]]
[[0.5615566 0.5615566]]
[[0.58609596 0.58609596]]
[[0.61055099 0.61055099]]
[[0.63492187 0.63492187]]
[[0.65920879 0.65920879]]
[[0.68341193 0.68341193]]
[[0.70753146 0.70753146]]
[[0.73156757 0.73156757]]
[[0.75552044 0.75552044]]
[[0.77939025 0.77939025]]
[[0.80317719 0.80317719]]
[[0.82688143 0.82688143]]
[[0.85050316 0.85050316]]
[[0.87404257 0.87404257]]
[[0.89749983 0.89749983]]
[[0.92087512 0.92087512]]
[[0.94416864

[[5.16788185 5.16788185]]
[[5.17259882 5.17259882]]
[[5.17728162 5.17728162]]
[[5.18193036 5.18193036]]
[[5.18654515 5.18654515]]
[[5.19112607 5.19112607]]
[[5.19567325 5.19567325]]
[[5.20018677 5.20018677]]
[[5.20466673 5.20466673]]
[[5.20911325 5.20911325]]
[[5.21352642 5.21352642]]
[[5.21790633 5.21790633]]
[[5.2222531 5.2222531]]
[[5.22656682 5.22656682]]
[[5.23084759 5.23084759]]
[[5.23509552 5.23509552]]
[[5.23931069 5.23931069]]
[[5.24349322 5.24349322]]
[[5.2476432 5.2476432]]
[[5.25176072 5.25176072]]
[[5.2558459 5.2558459]]
[[5.25989882 5.25989882]]
[[5.26391958 5.26391958]]
[[5.2679083 5.2679083]]
[[5.27186505 5.27186505]]
[[5.27578994 5.27578994]]
[[5.27968307 5.27968307]]
[[5.28354454 5.28354454]]
[[5.28737444 5.28737444]]
[[5.29117286 5.29117286]]
[[5.29493992 5.29493992]]
[[5.29867569 5.29867569]]
[[5.30238029 5.30238029]]
[[5.3060538 5.3060538]]
[[5.30969633 5.30969633]]
[[5.31330796 5.31330796]]
[[5.31688879 5.31688879]]
[[5.32043893 5.32043893]]
[[5.32395846 5.3239584

[[4.68078885 4.68078885]]
[[4.67734232 4.67734232]]
[[4.67389378 4.67389378]]
[[4.67044326 4.67044326]]
[[4.66699077 4.66699077]]
[[4.66353635 4.66353635]]
[[4.66008001 4.66008001]]
[[4.65662178 4.65662178]]
[[4.65316167 4.65316167]]
[[4.64969971 4.64969971]]
[[4.64623592 4.64623592]]
[[4.64277033 4.64277033]]
[[4.63930294 4.63930294]]
[[4.63583379 4.63583379]]
[[4.6323629 4.6323629]]
[[4.62889029 4.62889029]]
[[4.62541597 4.62541597]]
[[4.62193998 4.62193998]]
[[4.61846232 4.61846232]]
[[4.61498303 4.61498303]]
[[4.61150212 4.61150212]]
[[4.60801962 4.60801962]]
[[4.60453554 4.60453554]]
[[4.6010499 4.6010499]]
[[4.59756274 4.59756274]]
[[4.59407405 4.59407405]]
[[4.59058388 4.59058388]]
[[4.58709223 4.58709223]]
[[4.58359913 4.58359913]]
[[4.5801046 4.5801046]]
[[4.57660866 4.57660866]]
[[4.57311133 4.57311133]]
[[4.56961262 4.56961262]]
[[4.56611256 4.56611256]]
[[4.56261117 4.56261117]]
[[4.55910847 4.55910847]]
[[4.55560448 4.55560448]]
[[4.55209921 4.55209921]]
[[4.54859269 4.548

[[3.31068727 3.31068727]]
[[3.30753786 3.30753786]]
[[3.30439065 3.30439065]]
[[3.30124566 3.30124566]]
[[3.29810289 3.29810289]]
[[3.29496234 3.29496234]]
[[3.291824 3.291824]]
[[3.2886879 3.2886879]]
[[3.28555402 3.28555402]]
[[3.28242237 3.28242237]]
[[3.27929295 3.27929295]]
[[3.27616577 3.27616577]]
[[3.27304082 3.27304082]]
[[3.26991811 3.26991811]]
[[3.26679765 3.26679765]]
[[3.26367943 3.26367943]]
[[3.26056345 3.26056345]]
[[3.25744972 3.25744972]]
[[3.25433825 3.25433825]]
[[3.25122903 3.25122903]]
[[3.24812206 3.24812206]]
[[3.24501735 3.24501735]]
[[3.2419149 3.2419149]]
[[3.23881471 3.23881471]]
[[3.23571678 3.23571678]]
[[3.23262113 3.23262113]]
[[3.22952773 3.22952773]]
[[3.22643661 3.22643661]]
[[3.22334777 3.22334777]]
[[3.22026119 3.22026119]]
[[3.2171769 3.2171769]]
[[3.21409488 3.21409488]]
[[3.21101514 3.21101514]]
[[3.20793768 3.20793768]]
[[3.20486251 3.20486251]]
[[3.20178962 3.20178962]]
[[3.19871902 3.19871902]]
[[3.19565072 3.19565072]]
[[3.1925847 3.1925847]

[[2.3626291 2.3626291]]
[[2.36028333 2.36028333]]
[[2.35793979 2.35793979]]
[[2.35559847 2.35559847]]
[[2.35325937 2.35325937]]
[[2.35092249 2.35092249]]
[[2.34858783 2.34858783]]
[[2.34625538 2.34625538]]
[[2.34392515 2.34392515]]
[[2.34159713 2.34159713]]
[[2.33927132 2.33927132]]
[[2.33694772 2.33694772]]
[[2.33462633 2.33462633]]
[[2.33230715 2.33230715]]
[[2.32999018 2.32999018]]
[[2.3276754 2.3276754]]
[[2.32536284 2.32536284]]
[[2.32305247 2.32305247]]
[[2.3207443 2.3207443]]
[[2.31843834 2.31843834]]
[[2.31613457 2.31613457]]
[[2.31383299 2.31383299]]
[[2.31153361 2.31153361]]
[[2.30923642 2.30923642]]
[[2.30694143 2.30694143]]
[[2.30464862 2.30464862]]
[[2.302358 2.302358]]
[[2.30006957 2.30006957]]
[[2.29778333 2.29778333]]
[[2.29549926 2.29549926]]
[[2.29321738 2.29321738]]
[[2.29093769 2.29093769]]
[[2.28866017 2.28866017]]
[[2.28638483 2.28638483]]
[[2.28411166 2.28411166]]
[[2.28184067 2.28184067]]
[[2.27957186 2.27957186]]
[[2.27730521 2.27730521]]
[[2.27504074 2.2750407

[[1.30669685 1.30669685]]
[[1.30539024 1.30539024]]
[[1.30408494 1.30408494]]
[[1.30278094 1.30278094]]
[[1.30147825 1.30147825]]
[[1.30017686 1.30017686]]
[[1.29887677 1.29887677]]
[[1.29757798 1.29757798]]
[[1.29628049 1.29628049]]
[[1.29498429 1.29498429]]
[[1.29368939 1.29368939]]
[[1.29239578 1.29239578]]
[[1.29110346 1.29110346]]
[[1.28981244 1.28981244]]
[[1.28852271 1.28852271]]
[[1.28723426 1.28723426]]
[[1.28594711 1.28594711]]
[[1.28466124 1.28466124]]
[[1.28337665 1.28337665]]
[[1.28209335 1.28209335]]
[[1.28081133 1.28081133]]
[[1.27953059 1.27953059]]
[[1.27825114 1.27825114]]
[[1.27697296 1.27697296]]
[[1.27569606 1.27569606]]
[[1.27442043 1.27442043]]
[[1.27314608 1.27314608]]
[[1.271873 1.271873]]
[[1.2706012 1.2706012]]
[[1.26933066 1.26933066]]
[[1.2680614 1.2680614]]
[[1.26679341 1.26679341]]
[[1.26552668 1.26552668]]
[[1.26426122 1.26426122]]
[[1.26299702 1.26299702]]
[[1.26173409 1.26173409]]
[[1.26047241 1.26047241]]
[[1.259212 1.259212]]
[[1.25795285 1.25795285]

[[0.82141832 0.82141832]]
[[0.8205969 0.8205969]]
[[0.81977631 0.81977631]]
[[0.81895653 0.81895653]]
[[0.81813757 0.81813757]]
[[0.81731944 0.81731944]]
[[0.81650212 0.81650212]]
[[0.81568562 0.81568562]]
[[0.81486993 0.81486993]]
[[0.81405506 0.81405506]]
[[0.81324101 0.81324101]]
[[0.81242776 0.81242776]]
[[0.81161534 0.81161534]]
[[0.81080372 0.81080372]]
[[0.80999292 0.80999292]]
[[0.80918293 0.80918293]]
[[0.80837374 0.80837374]]
[[0.80756537 0.80756537]]
[[0.8067578 0.8067578]]
[[0.80595105 0.80595105]]
[[0.8051451 0.8051451]]
[[0.80433995 0.80433995]]
[[0.80353561 0.80353561]]
[[0.80273208 0.80273208]]
[[0.80192934 0.80192934]]
[[0.80112742 0.80112742]]
[[0.80032629 0.80032629]]
[[0.79952596 0.79952596]]
[[0.79872644 0.79872644]]
[[0.79792771 0.79792771]]
[[0.79712978 0.79712978]]
[[0.79633265 0.79633265]]
[[0.79553632 0.79553632]]
[[0.79474079 0.79474079]]
[[0.79394604 0.79394604]]
[[0.7931521 0.7931521]]
[[0.79235895 0.79235895]]
[[0.79156659 0.79156659]]
[[0.79077502 0.79077

In [21]:
my_nn=HandmadeNN(input_dim = 2)
    my_nn.add_dense_layer(1, 'linear',)
    X= np.ones((10_000, 2))
    y= np.zeros((10_000,1))
    my_nn.fit(X,y, loss='mse',optimizer_type='adam', batch_size=7, n_epochs=2)

    self.assertTrue (my_nn.score(X,y,'mse') < 0.5,\

IndentationError: unexpected indent (<ipython-input-21-ce040aecf5c6>, line 2)